CREATE PROC BRUTE_FORCE_DETECTION
AS

CREATE TABLE #LOG (LOGDATE DATETIME,PROCESSINFO VARCHAR(100),TEXT VARCHAR(MAX))
INSERT INTO #LOG EXEC XP_READERRORLOG

DECLARE @IP AS VARCHAR(20)
DECLARE @COUNT AS INT
DECLARE @BEGDATE AS DATETIME
DECLARE @ENDDATE AS DATETIME
DECLARE @TEXT AS VARCHAR(MAX)=''
DECLARE @MSG AS VARCHAR(1000)=''
DECLARE @SEQ AS INT

SELECT @COUNT=COUNT(*),@BEGDATE=MIN(LOGDATE),@ENDDATE=MAX(LOGDATE),@TEXT=TEXT
FROM #LOG WHERE TEXT LIKE 'login failed%' AND LOGDATE>=DATEADD(MINUTE,-1,GETDATE())
GROUP BY TEXT 
HAVING COUNT(LOGDATE)>100




SELECT @SEQ=SEQ FROM MASTER.dbo.splitString(@TEXT,' ')
WHERE word='[CLIENT:'

SELECT @IP=word FROM MASTER.dbo.splitString(@TEXT,' ')
WHERE SEQ=@SEQ+1
SET @IP=REPLACE(@IP,']','')


SET @MSG='Your system is under attack! A machine with IP:'+@IP+' has tried '+CONVERT(VARCHAR,@COUNT)+' wrong password between '+CONVERT(VARCHAR,@BEGDATE,108)+' and '+CONVERT(VARCHAR,@ENDDATE,108)
SELECT @MSG

IF @COUNT>100
BEGIN
INSERT INTO AUDIT.DBO.BRUTE_FORCE_ATTACK ([COMPUTERIP], [DATE_], [BEGDATE], [ENDDATE], [COUNT_])
VALUES(@IP,GETDATE(),@BEGDATE,@ENDDATE,@COUNT)
EXEC msdb.dbo.sp_send_dbmail  
    @profile_name = 'SQLMAIL',  
    @recipients = 'server.secure.nodque@gmail.com',  
    @body = @MSG,  
    @subject = 'WARNING! Brute Force Attack Dedected' ;  
END

DROP TABLE #LOG
